[[constraint]]
name = "github.com/sirupsen/logrus"
version = "1.8.1"

[[constraint]]
name = "github.com/spf13/viper"
version = "1.7.1"

[[constraint]]
name = "github.com/spf13/cobra"
version = "1.1.3"

[prune]
go-tests = false
unused-packages = false